import type { CommonFood } from "../types";

export const COMMON_FOODS: CommonFood[] = [
  // --- PROTEÍNAS (20) ---
  { translationKey: "chicken", calories: 110, protein: 23, carbs: 0, fat: 1.2, fiber: 0, ig: null, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "turkey", calories: 105, protein: 24, carbs: 0, fat: 1, fiber: 0, ig: null, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner", "breakfast"] },
  { translationKey: "egg", calories: 143, protein: 12.5, carbs: 0.7, fat: 9.5, fiber: 0, ig: null, sodiumLevel: "Medio", mealTags: ["breakfast", "lunch", "dinner"] },
  { translationKey: "salmon", calories: 208, protein: 20, carbs: 0, fat: 13, fiber: 0, ig: null, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "hake", calories: 89, protein: 18, carbs: 0, fat: 2, fiber: 0, ig: null, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "canned_tuna", calories: 116, protein: 26, carbs: 0, fat: 1, fiber: 0, ig: null, sodiumLevel: "Alto", mealTags: ["lunch", "dinner", "snack"] },
  { translationKey: "tofu", calories: 76, protein: 8, carbs: 1.9, fat: 4.8, fiber: 1.5, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "pork_loin", calories: 200, protein: 32, carbs: 0, fat: 8, fiber: 0, ig: null, sodiumLevel: "Alto", mealTags: ["lunch", "dinner"] },
  { translationKey: "prawns", calories: 99, protein: 24, carbs: 0, fat: 0.3, fiber: 0, ig: null, sodiumLevel: "Medio", mealTags: ["lunch", "dinner"] },
  { translationKey: "beef_lean", calories: 130, protein: 21, carbs: 0, fat: 5, fiber: 0, ig: null, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "cod", calories: 82, protein: 18, carbs: 0, fat: 0.7, fiber: 0, ig: null, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "sardines", calories: 208, protein: 24, carbs: 0, fat: 11, fiber: 0, ig: null, sodiumLevel: "Medio", mealTags: ["lunch", "dinner"] },
  { translationKey: "rabbit", calories: 136, protein: 20, carbs: 0, fat: 5.5, fiber: 0, ig: null, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "tempeh", calories: 193, protein: 19, carbs: 9, fat: 11, fiber: 6, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "seitan", calories: 370, protein: 75, carbs: 14, fat: 1.9, fiber: 0.6, ig: 15, sodiumLevel: "Alto", mealTags: ["lunch", "dinner"] },
  { translationKey: "cottage_cheese", calories: 98, protein: 11, carbs: 3.4, fat: 4.3, fiber: 0, ig: 10, sodiumLevel: "Medio", mealTags: ["breakfast", "snack"] },
  { translationKey: "skyr", calories: 65, protein: 11, carbs: 4, fat: 0.2, fiber: 0, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "egg_white", calories: 52, protein: 11, carbs: 0.7, fat: 0.2, fiber: 0, ig: null, sodiumLevel: "Medio", mealTags: ["breakfast", "lunch", "dinner"] },
  { translationKey: "whey_protein", calories: 375, protein: 80, carbs: 5, fat: 3, fiber: 0, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "octopus", calories: 82, protein: 15, carbs: 2.2, fat: 1, fiber: 0, ig: null, sodiumLevel: "Medio", mealTags: ["lunch", "dinner"] },
  // --- CARBOHIDRATOS (20) ---
  { translationKey: "oats", calories: 368, protein: 13, carbs: 64, fat: 7, fiber: 10, ig: 40, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "lentils", calories: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 8, ig: 25, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "chickpeas", calories: 164, protein: 9, carbs: 27, fat: 2.6, fiber: 7, ig: 30, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "quinoa", calories: 120, protein: 4.4, carbs: 21, fat: 1.9, fiber: 2.8, ig: 35, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "potato", calories: 77, protein: 2, carbs: 17, fat: 0.1, fiber: 2.2, ig: 70, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "sweet_potato", calories: 86, protein: 1.6, carbs: 20, fat: 0.1, fiber: 3, ig: 50, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "brown_rice", calories: 111, protein: 2.6, carbs: 23, fat: 0.9, fiber: 1.8, ig: 50, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "rye_bread", calories: 250, protein: 9, carbs: 46, fat: 3.3, fiber: 6, ig: 45, sodiumLevel: "Medio", mealTags: ["breakfast", "snack"] },
  { translationKey: "whole_pasta", calories: 124, protein: 5, carbs: 25, fat: 1, fiber: 3, ig: 45, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "black_beans", calories: 132, protein: 9, carbs: 23, fat: 0.5, fiber: 9, ig: 30, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "couscous", calories: 112, protein: 3.8, carbs: 23, fat: 0.2, fiber: 1.4, ig: 45, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "buckwheat", calories: 343, protein: 13, carbs: 71, fat: 3.4, fiber: 10, ig: 50, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "millet", calories: 378, protein: 11, carbs: 72, fat: 4.2, fiber: 8.5, ig: 55, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "peas", calories: 81, protein: 5, carbs: 14, fat: 0.4, fiber: 5, ig: 35, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "broad_beans", calories: 88, protein: 8, carbs: 10, fat: 0.6, fiber: 5, ig: 40, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "corn_cakes", calories: 387, protein: 8, carbs: 80, fat: 3, fiber: 4, ig: 85, sodiumLevel: "Medio", mealTags: ["breakfast", "snack"] },
  { translationKey: "cassava", calories: 160, protein: 1.4, carbs: 38, fat: 0.3, fiber: 1.8, ig: 55, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "bulgur", calories: 342, protein: 12, carbs: 76, fat: 1.3, fiber: 18, ig: 48, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "corn", calories: 86, protein: 3.2, carbs: 19, fat: 1.2, fiber: 2.7, ig: 55, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "amaranth", calories: 371, protein: 14, carbs: 65, fat: 7, fiber: 7, ig: 35, sodiumLevel: "Bajo", mealTags: ["breakfast", "lunch"] },
  // --- VEGETALES (30) ---
  { translationKey: "spinach", calories: 23, protein: 3, carbs: 3.6, fat: 0.4, fiber: 2.2, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner", "snack"] },
  { translationKey: "broccoli", calories: 34, protein: 2.8, carbs: 7, fat: 0.4, fiber: 2.6, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "zucchini", calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "asparagus", calories: 20, protein: 2.2, carbs: 3.7, fat: 0.1, fiber: 2.1, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "tomato", calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "lunch", "dinner", "snack"] },
  { translationKey: "red_pepper", calories: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner", "snack"] },
  { translationKey: "cucumber", calories: 15, protein: 0.6, carbs: 3.6, fat: 0.1, fiber: 0.5, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner", "snack"] },
  { translationKey: "eggplant", calories: 25, protein: 1, carbs: 6, fat: 0.2, fiber: 3, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "cauliflower", calories: 25, protein: 2, carbs: 5, fat: 0.3, fiber: 2, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "mushrooms", calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "lunch", "dinner"] },
  { translationKey: "artichoke", calories: 47, protein: 3.3, carbs: 11, fat: 0.2, fiber: 5, ig: 20, sodiumLevel: "Medio", mealTags: ["lunch", "dinner"] },
  { translationKey: "onion", calories: 40, protein: 1.1, carbs: 9, fat: 0.1, fiber: 1.7, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "carrot", calories: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, ig: 35, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner", "snack"] },
  { translationKey: "celery", calories: 16, protein: 0.7, carbs: 3, fat: 0.2, fiber: 1.6, ig: 15, sodiumLevel: "Alto", mealTags: ["lunch", "dinner", "snack"] },
  { translationKey: "radish", calories: 16, protein: 0.7, carbs: 3.4, fat: 0.1, fiber: 1.6, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner", "snack"] },
  { translationKey: "lambs_lettuce", calories: 21, protein: 2, carbs: 2, fat: 0.4, fiber: 1.5, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "arugula", calories: 25, protein: 2.6, carbs: 3.7, fat: 0.7, fiber: 1.6, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "green_beans", calories: 31, protein: 1.8, carbs: 7, fat: 0.2, fiber: 2.7, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "red_cabbage", calories: 31, protein: 1.4, carbs: 7, fat: 0.2, fiber: 2.1, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "leek", calories: 61, protein: 1.5, carbs: 14, fat: 0.3, fiber: 1.8, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "chard", calories: 19, protein: 1.8, carbs: 3.7, fat: 0.2, fiber: 1.6, ig: 15, sodiumLevel: "Alto", mealTags: ["lunch", "dinner"] },
  { translationKey: "escarole", calories: 17, protein: 1.2, carbs: 3.4, fat: 0.2, fiber: 3.1, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "endive", calories: 17, protein: 0.9, carbs: 4, fat: 0.1, fiber: 3.1, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "brussels_sprouts", calories: 43, protein: 3.4, carbs: 9, fat: 0.3, fiber: 3.8, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "fennel", calories: 31, protein: 1.2, carbs: 7, fat: 0.2, fiber: 3.1, ig: 15, sodiumLevel: "Medio", mealTags: ["lunch", "dinner"] },
  { translationKey: "pumpkin", calories: 26, protein: 1, carbs: 6.5, fat: 0.1, fiber: 0.5, ig: 75, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "garlic", calories: 149, protein: 6.4, carbs: 33, fat: 0.5, fiber: 2.1, ig: 30, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "chili", calories: 40, protein: 1.9, carbs: 9, fat: 0.4, fiber: 1.5, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "okra", calories: 33, protein: 1.9, carbs: 7, fat: 0.2, fiber: 3.2, ig: 20, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner"] },
  { translationKey: "soy_sprouts", calories: 30, protein: 3, carbs: 6, fat: 0.2, fiber: 1.8, ig: 15, sodiumLevel: "Bajo", mealTags: ["lunch", "dinner", "snack"] },
  // --- GRASAS SALUDABLES (15) ---
  { translationKey: "olive_oil", calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, ig: null, sodiumLevel: "Bajo", mealTags: ["breakfast", "lunch", "dinner"] },
  { translationKey: "avocado", calories: 160, protein: 2, carbs: 9, fat: 15, fiber: 7, ig: 10, sodiumLevel: "Bajo", mealTags: ["breakfast", "lunch", "dinner", "snack"] },
  { translationKey: "walnuts", calories: 654, protein: 15, carbs: 14, fat: 65, fiber: 7, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "almonds", calories: 579, protein: 21, carbs: 22, fat: 50, fiber: 12, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "chia_seeds", calories: 486, protein: 17, carbs: 42, fat: 31, fiber: 34, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "peanut_butter", calories: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "pistachios", calories: 562, protein: 20, carbs: 28, fat: 45, fiber: 10, ig: 15, sodiumLevel: "Bajo", mealTags: ["snack"] },
  { translationKey: "flaxseed", calories: 534, protein: 18, carbs: 29, fat: 42, fiber: 27, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "pumpkin_seeds", calories: 559, protein: 30, carbs: 10, fat: 49, fiber: 6, ig: 15, sodiumLevel: "Bajo", mealTags: ["snack"] },
  { translationKey: "olives", calories: 115, protein: 0.8, carbs: 6, fat: 10, fiber: 3.2, ig: 15, sodiumLevel: "Alto", mealTags: ["lunch", "dinner", "snack"] },
  { translationKey: "cashews", calories: 553, protein: 18, carbs: 30, fat: 44, fiber: 3.3, ig: 20, sodiumLevel: "Bajo", mealTags: ["snack"] },
  { translationKey: "hazelnuts", calories: 628, protein: 15, carbs: 17, fat: 61, fiber: 10, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "coconut_oil", calories: 862, protein: 0, carbs: 0, fat: 100, fiber: 0, ig: null, sodiumLevel: "Bajo", mealTags: ["breakfast", "lunch", "dinner"] },
  { translationKey: "ghee", calories: 899, protein: 0, carbs: 0, fat: 100, fiber: 0, ig: null, sodiumLevel: "Bajo", mealTags: ["breakfast", "lunch", "dinner"] },
  { translationKey: "macadamia", calories: 718, protein: 8, carbs: 14, fat: 76, fiber: 8.6, ig: 15, sodiumLevel: "Bajo", mealTags: ["snack"] },
  // --- FRUTAS Y LÁCTEOS (15) ---
  { translationKey: "blueberries", calories: 57, protein: 0.7, carbs: 14, fat: 0.3, fiber: 2.4, ig: 25, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "apple", calories: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, ig: 35, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "banana", calories: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, ig: 50, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "strawberries", calories: 32, protein: 0.7, carbs: 8, fat: 0.3, fiber: 2, ig: 25, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "lemon", calories: 29, protein: 1.1, carbs: 9, fat: 0.3, fiber: 2.8, ig: 20, sodiumLevel: "Bajo", mealTags: ["breakfast", "lunch", "dinner"] },
  { translationKey: "greek_yogurt", calories: 59, protein: 10, carbs: 3.6, fat: 0.4, fiber: 0, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "quark", calories: 68, protein: 12, carbs: 4, fat: 0.2, fiber: 0, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "kefir", calories: 37, protein: 3.3, carbs: 4, fat: 1, fiber: 0, ig: 15, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "kiwi", calories: 61, protein: 1.1, carbs: 15, fat: 0.5, fiber: 3, ig: 50, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "orange", calories: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4, ig: 40, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "pineapple", calories: 50, protein: 0.5, carbs: 13, fat: 0.1, fiber: 1.4, ig: 59, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "papaya", calories: 43, protein: 0.5, carbs: 11, fat: 0.3, fiber: 1.7, ig: 58, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "watermelon", calories: 30, protein: 0.6, carbs: 8, fat: 0.2, fiber: 0.4, ig: 72, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "raspberries", calories: 52, protein: 1.2, carbs: 12, fat: 0.7, fiber: 6.5, ig: 25, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
  { translationKey: "blackberry", calories: 43, protein: 1.4, carbs: 10, fat: 0.5, fiber: 5.3, ig: 25, sodiumLevel: "Bajo", mealTags: ["breakfast", "snack"] },
];

export interface Recipe {
  id: string;
  translationKey: string;
  cost?: string;
  time?: string;
  prepTime?: number;
  kcal?: number;
  calories?: number;
  protein: number;
  carbs: number;
  fat: number;
  mealTags?: string[];
}

export const RECIPES: Recipe[] = [
  { id: "r1", translationKey: "recipeDb.chicken_rice", cost: "≈ 1,80 €", time: "30 min", kcal: 520, protein: 38, carbs: 60, fat: 12 },
  { id: "r2", translationKey: "recipeDb.spinach_omelette", cost: "≈ 1,20 €", time: "15 min", kcal: 310, protein: 22, carbs: 6, fat: 22 },
  { id: "r3", translationKey: "recipeDb.quick_lentils", cost: "≈ 0,90 €", time: "20 min", kcal: 420, protein: 22, carbs: 55, fat: 8 },
  { id: "r4", translationKey: "recipeDb.tuna_pasta", cost: "≈ 1,40 €", time: "20 min", kcal: 540, protein: 28, carbs: 70, fat: 14 },
  { id: "r5", translationKey: "recipeDb.zucchini_cream", cost: "≈ 1,00 €", time: "25 min", kcal: 220, protein: 8, carbs: 18, fat: 12 },
  { id: "r6", translationKey: "recipeDb.chickpea_salad", cost: "≈ 1,10 €", time: "10 min", kcal: 410, protein: 18, carbs: 45, fat: 15 },
  { id: "r7", translationKey: "recipeDb.lemon_chicken_sweetpotato", cost: "≈ 2,00 €", time: "30 min", kcal: 450, protein: 35, carbs: 50, fat: 10 },
  { id: "r8", translationKey: "recipeDb.broken_eggs", cost: "≈ 1,30 €", time: "20 min", kcal: 480, protein: 20, carbs: 40, fat: 22 },
  { id: "r9", translationKey: "recipeDb.avocado_turkey_toast", cost: "≈ 1,50 €", time: "5 min", kcal: 320, protein: 15, carbs: 30, fat: 16 },
  { id: "r10", translationKey: "recipeDb.egg_white_mushroom", cost: "≈ 1,10 €", time: "15 min", kcal: 210, protein: 25, carbs: 5, fat: 10 },
  { id: "r11", translationKey: "recipeDb.apple_porridge", cost: "≈ 0,70 €", time: "10 min", kcal: 350, protein: 12, carbs: 60, fat: 6 },
  { id: "r12", translationKey: "recipeDb.stuffed_peppers_soy", cost: "≈ 1,80 €", time: "35 min", kcal: 380, protein: 25, carbs: 40, fat: 12 },
  { id: "r13", translationKey: "recipeDb.express_couscous", cost: "≈ 1,20 €", time: "10 min", kcal: 400, protein: 12, carbs: 70, fat: 5 },
  { id: "r14", translationKey: "recipeDb.grilled_eggplant_cheese", cost: "≈ 1,60 €", time: "20 min", kcal: 290, protein: 14, carbs: 12, fat: 18 },
  { id: "r15", translationKey: "protein_smoothie_bowl", cost: "≈ 1,50 €", time: "5 min", kcal: 310, protein: 25, carbs: 35, fat: 8 },
  // SEMANA 1 - DIETA MEDITERRÁNEA
  { id: 'rec_med_w1_l1', translationKey: 'recipes.med.w1_l1', prepTime: 40, calories: 350, protein: 20, carbs: 45, fat: 10, mealTags: ['lunch'] },
  { id: 'rec_med_w1_d1', translationKey: 'recipes.med.w1_d1', prepTime: 20, calories: 450, protein: 42, carbs: 12, fat: 26, mealTags: ['dinner'] },
  { id: 'rec_med_w1_l2', translationKey: 'recipes.med.w1_l2', prepTime: 30, calories: 650, protein: 55, carbs: 40, fat: 30, mealTags: ['lunch'] },
  { id: 'rec_med_w1_d2', translationKey: 'recipes.med.w1_d2', prepTime: 15, calories: 450, protein: 38, carbs: 15, fat: 26, mealTags: ['dinner'] },
  { id: 'rec_med_w1_l3', translationKey: 'recipes.med.w1_l3', prepTime: 15, calories: 650, protein: 30, carbs: 65, fat: 30, mealTags: ['lunch'] },
  { id: 'rec_med_w1_d3', translationKey: 'recipes.med.w1_d3', prepTime: 15, calories: 450, protein: 25, carbs: 10, fat: 34, mealTags: ['dinner'] },
  { id: 'rec_med_w1_l4', translationKey: 'recipes.med.w1_l4', prepTime: 40, calories: 650, protein: 45, carbs: 60, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_med_w1_d4', translationKey: 'recipes.med.w1_d4', prepTime: 15, calories: 450, protein: 35, carbs: 15, fat: 27, mealTags: ['dinner'] },
  { id: 'rec_med_w1_l5', translationKey: 'recipes.med.w1_l5', prepTime: 20, calories: 650, protein: 40, carbs: 65, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_med_w1_d5', translationKey: 'recipes.med.w1_d5', prepTime: 15, calories: 450, protein: 45, carbs: 25, fat: 18, mealTags: ['dinner'] },
  { id: 'rec_med_w1_l6', translationKey: 'recipes.med.w1_l6', prepTime: 30, calories: 650, protein: 35, carbs: 70, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_med_w1_d6', translationKey: 'recipes.med.w1_d6', prepTime: 20, calories: 450, protein: 40, carbs: 35, fat: 16, mealTags: ['dinner'] },
  { id: 'rec_med_w1_l7', translationKey: 'recipes.med.w1_l7', prepTime: 25, calories: 650, protein: 45, carbs: 30, fat: 38, mealTags: ['lunch'] },
  { id: 'rec_med_w1_d7', translationKey: 'recipes.med.w1_d7', prepTime: 10, calories: 450, protein: 25, carbs: 35, fat: 23, mealTags: ['dinner'] },
  // SEMANA 2 - DIETA MEDITERRÁNEA
  { id: 'rec_med_w2_l1', translationKey: 'recipes.med.w2_l1', prepTime: 15, calories: 650, protein: 45, carbs: 60, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_med_w2_d1', translationKey: 'recipes.med.w2_d1', prepTime: 20, calories: 450, protein: 35, carbs: 40, fat: 15, mealTags: ['dinner'] },
  { id: 'rec_med_w2_l2', translationKey: 'recipes.med.w2_l2', prepTime: 35, calories: 650, protein: 50, carbs: 45, fat: 30, mealTags: ['lunch'] },
  { id: 'rec_med_w2_d2', translationKey: 'recipes.med.w2_d2', prepTime: 15, calories: 450, protein: 30, carbs: 10, fat: 32, mealTags: ['dinner'] },
  { id: 'rec_med_w2_l3', translationKey: 'recipes.med.w2_l3', prepTime: 20, calories: 650, protein: 40, carbs: 70, fat: 20, mealTags: ['lunch'] },
  { id: 'rec_med_w2_d3', translationKey: 'recipes.med.w2_d3', prepTime: 25, calories: 450, protein: 35, carbs: 25, fat: 23, mealTags: ['dinner'] },
  { id: 'rec_med_w2_l4', translationKey: 'recipes.med.w2_l4', prepTime: 40, calories: 650, protein: 30, carbs: 80, fat: 20, mealTags: ['lunch'] },
  { id: 'rec_med_w2_d4', translationKey: 'recipes.med.w2_d4', prepTime: 15, calories: 450, protein: 40, carbs: 15, fat: 25, mealTags: ['dinner'] },
  { id: 'rec_med_w2_l5', translationKey: 'recipes.med.w2_l5', prepTime: 20, calories: 650, protein: 45, carbs: 50, fat: 28, mealTags: ['lunch'] },
  { id: 'rec_med_w2_d5', translationKey: 'recipes.med.w2_d5', prepTime: 25, calories: 450, protein: 15, carbs: 50, fat: 20, mealTags: ['dinner'] },
  { id: 'rec_med_w2_l6', translationKey: 'recipes.med.w2_l6', prepTime: 20, calories: 650, protein: 40, carbs: 65, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_med_w2_d6', translationKey: 'recipes.med.w2_d6', prepTime: 15, calories: 450, protein: 35, carbs: 30, fat: 20, mealTags: ['dinner'] },
  { id: 'rec_med_w2_l7', translationKey: 'recipes.med.w2_l7', prepTime: 35, calories: 650, protein: 45, carbs: 55, fat: 27, mealTags: ['lunch'] },
  { id: 'rec_med_w2_d7', translationKey: 'recipes.med.w2_d7', prepTime: 10, calories: 450, protein: 30, carbs: 35, fat: 22, mealTags: ['dinner'] },
  // SEMANA 3 - DIETA MEDITERRÁNEA
  { id: 'rec_med_w3_l1', translationKey: 'recipes.med.w3_l1', prepTime: 25, calories: 650, protein: 35, carbs: 70, fat: 22, mealTags: ['lunch'] },
  { id: 'rec_med_w3_d1', translationKey: 'recipes.med.w3_d1', prepTime: 15, calories: 450, protein: 45, carbs: 20, fat: 18, mealTags: ['dinner'] },
  { id: 'rec_med_w3_l2', translationKey: 'recipes.med.w3_l2', prepTime: 25, calories: 650, protein: 40, carbs: 45, fat: 35, mealTags: ['lunch'] },
  { id: 'rec_med_w3_d2', translationKey: 'recipes.med.w3_d2', prepTime: 20, calories: 450, protein: 20, carbs: 40, fat: 22, mealTags: ['dinner'] },
  { id: 'rec_med_w3_l3', translationKey: 'recipes.med.w3_l3', prepTime: 35, calories: 650, protein: 35, carbs: 65, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_med_w3_d3', translationKey: 'recipes.med.w3_d3', prepTime: 20, calories: 450, protein: 40, carbs: 25, fat: 20, mealTags: ['dinner'] },
  { id: 'rec_med_w3_l4', translationKey: 'recipes.med.w3_l4', prepTime: 25, calories: 650, protein: 45, carbs: 60, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_med_w3_d4', translationKey: 'recipes.med.w3_d4', prepTime: 15, calories: 450, protein: 25, carbs: 15, fat: 32, mealTags: ['dinner'] },
  { id: 'rec_med_w3_l5', translationKey: 'recipes.med.w3_l5', prepTime: 20, calories: 650, protein: 45, carbs: 35, fat: 35, mealTags: ['lunch'] },
  { id: 'rec_med_w3_d5', translationKey: 'recipes.med.w3_d5', prepTime: 10, calories: 450, protein: 35, carbs: 15, fat: 28, mealTags: ['dinner'] },
  { id: 'rec_med_w3_l6', translationKey: 'recipes.med.w3_l6', prepTime: 90, calories: 650, protein: 50, carbs: 40, fat: 30, mealTags: ['lunch'] },
  { id: 'rec_med_w3_d6', translationKey: 'recipes.med.w3_d6', prepTime: 20, calories: 450, protein: 35, carbs: 20, fat: 25, mealTags: ['dinner'] },
  { id: 'rec_med_w3_l7', translationKey: 'recipes.med.w3_l7', prepTime: 20, calories: 650, protein: 25, carbs: 60, fat: 35, mealTags: ['lunch'] },
  { id: 'rec_med_w3_d7', translationKey: 'recipes.med.w3_d7', prepTime: 15, calories: 450, protein: 30, carbs: 35, fat: 20, mealTags: ['dinner'] },
  // SEMANA 4 - DIETA MEDITERRÁNEA
  { id: 'rec_med_w4_l1', translationKey: 'recipes.med.w4_l1', prepTime: 35, calories: 650, protein: 45, carbs: 60, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_med_w4_d1', translationKey: 'recipes.med.w4_d1', prepTime: 15, calories: 450, protein: 35, carbs: 15, fat: 25, mealTags: ['dinner'] },
  { id: 'rec_med_w4_l2', translationKey: 'recipes.med.w4_l2', prepTime: 30, calories: 650, protein: 30, carbs: 70, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_med_w4_d2', translationKey: 'recipes.med.w4_d2', prepTime: 15, calories: 450, protein: 20, carbs: 25, fat: 28, mealTags: ['dinner'] },
  { id: 'rec_med_w4_l3', translationKey: 'recipes.med.w4_l3', prepTime: 20, calories: 650, protein: 35, carbs: 65, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_med_w4_d3', translationKey: 'recipes.med.w4_d3', prepTime: 25, calories: 450, protein: 45, carbs: 20, fat: 20, mealTags: ['dinner'] },
  { id: 'rec_med_w4_l4', translationKey: 'recipes.med.w4_l4', prepTime: 15, calories: 650, protein: 40, carbs: 55, fat: 30, mealTags: ['lunch'] },
  { id: 'rec_med_w4_d4', translationKey: 'recipes.med.w4_d4', prepTime: 20, calories: 450, protein: 40, carbs: 15, fat: 25, mealTags: ['dinner'] },
  { id: 'rec_med_w4_l5', translationKey: 'recipes.med.w4_l5', prepTime: 35, calories: 650, protein: 45, carbs: 65, fat: 20, mealTags: ['lunch'] },
  { id: 'rec_med_w4_d5', translationKey: 'recipes.med.w4_d5', prepTime: 10, calories: 450, protein: 35, carbs: 10, fat: 28, mealTags: ['dinner'] },
  { id: 'rec_med_w4_l6', translationKey: 'recipes.med.w4_l6', prepTime: 40, calories: 650, protein: 40, carbs: 55, fat: 28, mealTags: ['lunch'] },
  { id: 'rec_med_w4_d6', translationKey: 'recipes.med.w4_d6', prepTime: 15, calories: 450, protein: 40, carbs: 20, fat: 22, mealTags: ['dinner'] },
  { id: 'rec_med_w4_l7', translationKey: 'recipes.med.w4_l7', prepTime: 45, calories: 650, protein: 35, carbs: 60, fat: 28, mealTags: ['lunch'] },
  { id: 'rec_med_w4_d7', translationKey: 'recipes.med.w4_d7', prepTime: 10, calories: 450, protein: 25, carbs: 30, fat: 25, mealTags: ['dinner'] },
  // SEMANA 1 - DIETA LOW-CARB
  { id: 'rec_lc_w1_l1', translationKey: 'recipes.low_carb.w1_l1', prepTime: 20, calories: 650, protein: 55, carbs: 12, fat: 40, mealTags: ['lunch'] },
  { id: 'rec_lc_w1_d1', translationKey: 'recipes.low_carb.w1_d1', prepTime: 15, calories: 500, protein: 45, carbs: 8, fat: 32, mealTags: ['dinner'] },
  { id: 'rec_lc_w1_l2', translationKey: 'recipes.low_carb.w1_l2', prepTime: 10, calories: 650, protein: 50, carbs: 10, fat: 42, mealTags: ['lunch'] },
  { id: 'rec_lc_w1_d2', translationKey: 'recipes.low_carb.w1_d2', prepTime: 15, calories: 500, protein: 42, carbs: 10, fat: 32, mealTags: ['dinner'] },
  { id: 'rec_lc_w1_l3', translationKey: 'recipes.low_carb.w1_l3', prepTime: 25, calories: 650, protein: 45, carbs: 12, fat: 45, mealTags: ['lunch'] },
  { id: 'rec_lc_w1_d3', translationKey: 'recipes.low_carb.w1_d3', prepTime: 15, calories: 500, protein: 45, carbs: 5, fat: 33, mealTags: ['dinner'] },
  { id: 'rec_lc_w1_l4', translationKey: 'recipes.low_carb.w1_l4', prepTime: 35, calories: 650, protein: 55, carbs: 15, fat: 38, mealTags: ['lunch'] },
  { id: 'rec_lc_w1_d4', translationKey: 'recipes.low_carb.w1_d4', prepTime: 20, calories: 500, protein: 40, carbs: 12, fat: 32, mealTags: ['dinner'] },
  { id: 'rec_lc_w1_l5', translationKey: 'recipes.low_carb.w1_l5', prepTime: 20, calories: 650, protein: 50, carbs: 10, fat: 42, mealTags: ['lunch'] },
  { id: 'rec_lc_w1_d5', translationKey: 'recipes.low_carb.w1_d5', prepTime: 20, calories: 500, protein: 40, carbs: 12, fat: 32, mealTags: ['dinner'] },
  { id: 'rec_lc_w1_l6', translationKey: 'recipes.low_carb.w1_l6', prepTime: 20, calories: 650, protein: 50, carbs: 15, fat: 40, mealTags: ['lunch'] },
  { id: 'rec_lc_w1_d6', translationKey: 'recipes.low_carb.w1_d6', prepTime: 25, calories: 500, protein: 45, carbs: 10, fat: 30, mealTags: ['dinner'] },
  { id: 'rec_lc_w1_l7', translationKey: 'recipes.low_carb.w1_l7', prepTime: 25, calories: 650, protein: 55, carbs: 12, fat: 40, mealTags: ['lunch'] },
  { id: 'rec_lc_w1_d7', translationKey: 'recipes.low_carb.w1_d7', prepTime: 15, calories: 500, protein: 40, carbs: 8, fat: 34, mealTags: ['dinner'] },
  // SEMANA 2 - DIETA LOW-CARB
  { id: 'rec_lc_w2_l1', translationKey: 'recipes.low_carb.w2_l1', prepTime: 20, calories: 650, protein: 50, carbs: 10, fat: 45, mealTags: ['lunch'] },
  { id: 'rec_lc_w2_d1', translationKey: 'recipes.low_carb.w2_d1', prepTime: 25, calories: 500, protein: 42, carbs: 8, fat: 33, mealTags: ['dinner'] },
  { id: 'rec_lc_w2_l2', translationKey: 'recipes.low_carb.w2_l2', prepTime: 20, calories: 650, protein: 45, carbs: 12, fat: 46, mealTags: ['lunch'] },
  { id: 'rec_lc_w2_d2', translationKey: 'recipes.low_carb.w2_d2', prepTime: 30, calories: 500, protein: 40, carbs: 15, fat: 31, mealTags: ['dinner'] },
  { id: 'rec_lc_w2_l3', translationKey: 'recipes.low_carb.w2_l3', prepTime: 25, calories: 650, protein: 48, carbs: 5, fat: 48, mealTags: ['lunch'] },
  { id: 'rec_lc_w2_d3', translationKey: 'recipes.low_carb.w2_d3', prepTime: 20, calories: 500, protein: 45, carbs: 12, fat: 30, mealTags: ['dinner'] },
  { id: 'rec_lc_w2_l4', translationKey: 'recipes.low_carb.w2_l4', prepTime: 15, calories: 650, protein: 50, carbs: 8, fat: 46, mealTags: ['lunch'] },
  { id: 'rec_lc_w2_d4', translationKey: 'recipes.low_carb.w2_d4', prepTime: 15, calories: 500, protein: 40, carbs: 5, fat: 35, mealTags: ['dinner'] },
  { id: 'rec_lc_w2_l5', translationKey: 'recipes.low_carb.w2_l5', prepTime: 25, calories: 650, protein: 45, carbs: 10, fat: 47, mealTags: ['lunch'] },
  { id: 'rec_lc_w2_d5', translationKey: 'recipes.low_carb.w2_d5', prepTime: 15, calories: 500, protein: 42, carbs: 5, fat: 34, mealTags: ['dinner'] },
  { id: 'rec_lc_w2_l6', translationKey: 'recipes.low_carb.w2_l6', prepTime: 10, calories: 650, protein: 55, carbs: 8, fat: 44, mealTags: ['lunch'] },
  { id: 'rec_lc_w2_d6', translationKey: 'recipes.low_carb.w2_d6', prepTime: 15, calories: 500, protein: 40, carbs: 10, fat: 33, mealTags: ['dinner'] },
  { id: 'rec_lc_w2_l7', translationKey: 'recipes.low_carb.w2_l7', prepTime: 20, calories: 650, protein: 50, carbs: 12, fat: 44, mealTags: ['lunch'] },
  { id: 'rec_lc_w2_d7', translationKey: 'recipes.low_carb.w2_d7', prepTime: 35, calories: 500, protein: 45, carbs: 10, fat: 31, mealTags: ['dinner'] },
  // SEMANA 3 - DIETA LOW-CARB
  { id: 'rec_lc_w3_l1', translationKey: 'recipes.low_carb.w3_l1', prepTime: 20, calories: 650, protein: 55, carbs: 10, fat: 43, mealTags: ['lunch'] },
  { id: 'rec_lc_w3_d1', translationKey: 'recipes.low_carb.w3_d1', prepTime: 25, calories: 500, protein: 40, carbs: 15, fat: 31, mealTags: ['dinner'] },
  { id: 'rec_lc_w3_l2', translationKey: 'recipes.low_carb.w3_l2', prepTime: 20, calories: 650, protein: 50, carbs: 12, fat: 44, mealTags: ['lunch'] },
  { id: 'rec_lc_w3_d2', translationKey: 'recipes.low_carb.w3_d2', prepTime: 10, calories: 500, protein: 35, carbs: 12, fat: 34, mealTags: ['dinner'] },
  { id: 'rec_lc_w3_l3', translationKey: 'recipes.low_carb.w3_l3', prepTime: 25, calories: 650, protein: 45, carbs: 15, fat: 45, mealTags: ['lunch'] },
  { id: 'rec_lc_w3_d3', translationKey: 'recipes.low_carb.w3_d3', prepTime: 25, calories: 500, protein: 42, carbs: 10, fat: 32, mealTags: ['dinner'] },
  { id: 'rec_lc_w3_l4', translationKey: 'recipes.low_carb.w3_l4', prepTime: 30, calories: 650, protein: 48, carbs: 8, fat: 47, mealTags: ['lunch'] },
  { id: 'rec_lc_w3_d4', translationKey: 'recipes.low_carb.w3_d4', prepTime: 20, calories: 500, protein: 45, carbs: 15, fat: 28, mealTags: ['dinner'] },
  { id: 'rec_lc_w3_l5', translationKey: 'recipes.low_carb.w3_l5', prepTime: 35, calories: 650, protein: 50, carbs: 12, fat: 44, mealTags: ['lunch'] },
  { id: 'rec_lc_w3_d5', translationKey: 'recipes.low_carb.w3_d5', prepTime: 15, calories: 500, protein: 38, carbs: 10, fat: 34, mealTags: ['dinner'] },
  { id: 'rec_lc_w3_l6', translationKey: 'recipes.low_carb.w3_l6', prepTime: 20, calories: 650, protein: 55, carbs: 10, fat: 43, mealTags: ['lunch'] },
  { id: 'rec_lc_w3_d6', translationKey: 'recipes.low_carb.w3_d6', prepTime: 20, calories: 500, protein: 40, carbs: 5, fat: 35, mealTags: ['dinner'] },
  { id: 'rec_lc_w3_l7', translationKey: 'recipes.low_carb.w3_l7', prepTime: 25, calories: 650, protein: 45, carbs: 8, fat: 48, mealTags: ['lunch'] },
  { id: 'rec_lc_w3_d7', translationKey: 'recipes.low_carb.w3_d7', prepTime: 15, calories: 500, protein: 35, carbs: 15, fat: 33, mealTags: ['dinner'] },
  // SEMANA 4 - DIETA LOW-CARB
  { id: 'rec_lc_w4_l1', translationKey: 'recipes.low_carb.w4_l1', prepTime: 20, calories: 650, protein: 50, carbs: 12, fat: 44, mealTags: ['lunch'] },
  { id: 'rec_lc_w4_d1', translationKey: 'recipes.low_carb.w4_d1', prepTime: 25, calories: 500, protein: 42, carbs: 8, fat: 33, mealTags: ['dinner'] },
  { id: 'rec_lc_w4_l2', translationKey: 'recipes.low_carb.w4_l2', prepTime: 30, calories: 650, protein: 48, carbs: 10, fat: 45, mealTags: ['lunch'] },
  { id: 'rec_lc_w4_d2', translationKey: 'recipes.low_carb.w4_d2', prepTime: 15, calories: 500, protein: 40, carbs: 12, fat: 32, mealTags: ['dinner'] },
  { id: 'rec_lc_w4_l3', translationKey: 'recipes.low_carb.w4_l3', prepTime: 20, calories: 650, protein: 45, carbs: 8, fat: 48, mealTags: ['lunch'] },
  { id: 'rec_lc_w4_d3', translationKey: 'recipes.low_carb.w4_d3', prepTime: 10, calories: 500, protein: 45, carbs: 10, fat: 31, mealTags: ['dinner'] },
  { id: 'rec_lc_w4_l4', translationKey: 'recipes.low_carb.w4_l4', prepTime: 25, calories: 650, protein: 55, carbs: 15, fat: 40, mealTags: ['lunch'] },
  { id: 'rec_lc_w4_d4', translationKey: 'recipes.low_carb.w4_d4', prepTime: 15, calories: 500, protein: 40, carbs: 5, fat: 35, mealTags: ['dinner'] },
  { id: 'rec_lc_w4_l5', translationKey: 'recipes.low_carb.w4_l5', prepTime: 25, calories: 650, protein: 50, carbs: 12, fat: 44, mealTags: ['lunch'] },
  { id: 'rec_lc_w4_d5', translationKey: 'recipes.low_carb.w4_d5', prepTime: 20, calories: 500, protein: 45, carbs: 8, fat: 32, mealTags: ['dinner'] },
  { id: 'rec_lc_w4_l6', translationKey: 'recipes.low_carb.w4_l6', prepTime: 30, calories: 650, protein: 45, carbs: 10, fat: 47, mealTags: ['lunch'] },
  { id: 'rec_lc_w4_d6', translationKey: 'recipes.low_carb.w4_d6', prepTime: 15, calories: 500, protein: 42, carbs: 5, fat: 34, mealTags: ['dinner'] },
  { id: 'rec_lc_w4_l7', translationKey: 'recipes.low_carb.w4_l7', prepTime: 35, calories: 650, protein: 50, carbs: 15, fat: 42, mealTags: ['lunch'] },
  { id: 'rec_lc_w4_d7', translationKey: 'recipes.low_carb.w4_d7', prepTime: 25, calories: 500, protein: 48, carbs: 5, fat: 32, mealTags: ['dinner'] },
  // SEMANA 1 - DIETA VEGETARIANA
  { id: 'rec_veg_w1_l1', translationKey: 'recipes.veg.w1_l1', prepTime: 35, calories: 650, protein: 25, carbs: 80, fat: 22, mealTags: ['lunch'] },
  { id: 'rec_veg_w1_d1', translationKey: 'recipes.veg.w1_d1', prepTime: 15, calories: 450, protein: 22, carbs: 35, fat: 25, mealTags: ['dinner'] },
  { id: 'rec_veg_w1_l2', translationKey: 'recipes.veg.w1_l2', prepTime: 25, calories: 650, protein: 24, carbs: 85, fat: 20, mealTags: ['lunch'] },
  { id: 'rec_veg_w1_d2', translationKey: 'recipes.veg.w1_d2', prepTime: 20, calories: 450, protein: 20, carbs: 40, fat: 23, mealTags: ['dinner'] },
  { id: 'rec_veg_w1_l3', translationKey: 'recipes.veg.w1_l3', prepTime: 20, calories: 650, protein: 28, carbs: 85, fat: 18, mealTags: ['lunch'] },
  { id: 'rec_veg_w1_d3', translationKey: 'recipes.veg.w1_d3', prepTime: 15, calories: 450, protein: 24, carbs: 20, fat: 28, mealTags: ['dinner'] },
  { id: 'rec_veg_w1_l4', translationKey: 'recipes.veg.w1_l4', prepTime: 20, calories: 650, protein: 28, carbs: 75, fat: 25, mealTags: ['lunch'] },
  { id: 'rec_veg_w1_d4', translationKey: 'recipes.veg.w1_d4', prepTime: 25, calories: 450, protein: 18, carbs: 45, fat: 20, mealTags: ['dinner'] },
  { id: 'rec_veg_w1_l5', translationKey: 'recipes.veg.w1_l5', prepTime: 30, calories: 650, protein: 26, carbs: 80, fat: 22, mealTags: ['lunch'] },
  { id: 'rec_veg_w1_d5', translationKey: 'recipes.veg.w1_d5', prepTime: 35, calories: 450, protein: 20, carbs: 55, fat: 16, mealTags: ['dinner'] },
  { id: 'rec_veg_w1_l6', translationKey: 'recipes.veg.w1_l6', prepTime: 40, calories: 650, protein: 22, carbs: 90, fat: 20, mealTags: ['lunch'] },
  { id: 'rec_veg_w1_d6', translationKey: 'recipes.veg.w1_d6', prepTime: 15, calories: 450, protein: 24, carbs: 35, fat: 22, mealTags: ['dinner'] },
  { id: 'rec_veg_w1_l7', translationKey: 'recipes.veg.w1_l7', prepTime: 20, calories: 650, protein: 26, carbs: 70, fat: 28, mealTags: ['lunch'] },
  { id: 'rec_veg_w1_d7', translationKey: 'recipes.veg.w1_d7', prepTime: 10, calories: 450, protein: 22, carbs: 40, fat: 22, mealTags: ['dinner'] }
];

import type { DailyMenuPlan } from "../types";

export const MEDITERRANEAN_PLAN: DailyMenuPlan[] = [
  // SEMANA 1
  { id: 'm_w1_d1', week: 1, day: 1, translationKey: 'plans.med.w1_d1', totalKcal: 1750 },
  { id: 'm_w1_d2', week: 1, day: 2, translationKey: 'plans.med.w1_d2', totalKcal: 1820 },
  { id: 'm_w1_d3', week: 1, day: 3, translationKey: 'plans.med.w1_d3', totalKcal: 1790 },
  { id: 'm_w1_d4', week: 1, day: 4, translationKey: 'plans.med.w1_d4', totalKcal: 1880 },
  { id: 'm_w1_d5', week: 1, day: 5, translationKey: 'plans.med.w1_d5', totalKcal: 1810 },
  { id: 'm_w1_d6', week: 1, day: 6, translationKey: 'plans.med.w1_d6', totalKcal: 1850 },
  { id: 'm_w1_d7', week: 1, day: 7, translationKey: 'plans.med.w1_d7', totalKcal: 1780 },
  // SEMANA 2
  { id: 'm_w2_d1', week: 2, day: 8, translationKey: 'plans.med.w2_d1', totalKcal: 1780, warnings: ['high_sodium'] },
  { id: 'm_w2_d2', week: 2, day: 9, translationKey: 'plans.med.w2_d2', totalKcal: 1820 },
  { id: 'm_w2_d3', week: 2, day: 10, translationKey: 'plans.med.w2_d3', totalKcal: 1850 },
  { id: 'm_w2_d4', week: 2, day: 11, translationKey: 'plans.med.w2_d4', totalKcal: 1870 },
  { id: 'm_w2_d5', week: 2, day: 12, translationKey: 'plans.med.w2_d5', totalKcal: 1790 },
  { id: 'm_w2_d6', week: 2, day: 13, translationKey: 'plans.med.w2_d6', totalKcal: 1830 },
  { id: 'm_w2_d7', week: 2, day: 14, translationKey: 'plans.med.w2_d7', totalKcal: 1810, warnings: ['high_sodium'] },
  // SEMANA 3
  { id: 'm_w3_d1', week: 3, day: 15, translationKey: 'plans.med.w3_d1', totalKcal: 1750, warnings: ['high_potassium'] },
  { id: 'm_w3_d2', week: 3, day: 16, translationKey: 'plans.med.w3_d2', totalKcal: 1820, warnings: ['high_potassium'] },
  { id: 'm_w3_d3', week: 3, day: 17, translationKey: 'plans.med.w3_d3', totalKcal: 1840 },
  { id: 'm_w3_d4', week: 3, day: 18, translationKey: 'plans.med.w3_d4', totalKcal: 1880 },
  { id: 'm_w3_d5', week: 3, day: 19, translationKey: 'plans.med.w3_d5', totalKcal: 1790 },
  { id: 'm_w3_d6', week: 3, day: 20, translationKey: 'plans.med.w3_d6', totalKcal: 1860 },
  { id: 'm_w3_d7', week: 3, day: 21, translationKey: 'plans.med.w3_d7', totalKcal: 1810 },
  // SEMANA 4
  { id: 'm_w4_d1', week: 4, day: 22, translationKey: 'plans.med.w4_d1', totalKcal: 1780 },
  { id: 'm_w4_d2', week: 4, day: 23, translationKey: 'plans.med.w4_d2', totalKcal: 1820 },
  { id: 'm_w4_d3', week: 4, day: 24, translationKey: 'plans.med.w4_d3', totalKcal: 1850 },
  { id: 'm_w4_d4', week: 4, day: 25, translationKey: 'plans.med.w4_d4', totalKcal: 1870 },
  { id: 'm_w4_d5', week: 4, day: 26, translationKey: 'plans.med.w4_d5', totalKcal: 1810 },
  { id: 'm_w4_d6', week: 4, day: 27, translationKey: 'plans.med.w4_d6', totalKcal: 1840 },
  { id: 'm_w4_d7', week: 4, day: 28, translationKey: 'plans.med.w4_d7', totalKcal: 1890 },
];

export const LOW_CARB_PLAN: DailyMenuPlan[] = [
  // SEMANA 1
  { id: 'lc_w1_d1', week: 1, day: 1, translationKey: 'plans.low_carb.w1_d1', totalKcal: 1850 },
  { id: 'lc_w1_d2', week: 1, day: 2, translationKey: 'plans.low_carb.w1_d2', totalKcal: 1850 },
  { id: 'lc_w1_d3', week: 1, day: 3, translationKey: 'plans.low_carb.w1_d3', totalKcal: 1850 },
  { id: 'lc_w1_d4', week: 1, day: 4, translationKey: 'plans.low_carb.w1_d4', totalKcal: 1850 },
  { id: 'lc_w1_d5', week: 1, day: 5, translationKey: 'plans.low_carb.w1_d5', totalKcal: 1850 },
  { id: 'lc_w1_d6', week: 1, day: 6, translationKey: 'plans.low_carb.w1_d6', totalKcal: 1850 },
  { id: 'lc_w1_d7', week: 1, day: 7, translationKey: 'plans.low_carb.w1_d7', totalKcal: 1850 },
  // SEMANA 2
  { id: 'lc_w2_d1', week: 2, day: 8, translationKey: 'plans.low_carb.w2_d1', totalKcal: 1850 },
  { id: 'lc_w2_d2', week: 2, day: 9, translationKey: 'plans.low_carb.w2_d2', totalKcal: 1850 },
  { id: 'lc_w2_d3', week: 2, day: 10, translationKey: 'plans.low_carb.w2_d3', totalKcal: 1850 },
  { id: 'lc_w2_d4', week: 2, day: 11, translationKey: 'plans.low_carb.w2_d4', totalKcal: 1850 },
  { id: 'lc_w2_d5', week: 2, day: 12, translationKey: 'plans.low_carb.w2_d5', totalKcal: 1850 },
  { id: 'lc_w2_d6', week: 2, day: 13, translationKey: 'plans.low_carb.w2_d6', totalKcal: 1850 },
  { id: 'lc_w2_d7', week: 2, day: 14, translationKey: 'plans.low_carb.w2_d7', totalKcal: 1850 },
  // SEMANA 3
  { id: 'lc_w3_d1', week: 3, day: 15, translationKey: 'plans.low_carb.w3_d1', totalKcal: 1850 },
  { id: 'lc_w3_d2', week: 3, day: 16, translationKey: 'plans.low_carb.w3_d2', totalKcal: 1850 },
  { id: 'lc_w3_d3', week: 3, day: 17, translationKey: 'plans.low_carb.w3_d3', totalKcal: 1850, warnings: ['high_sodium'] },
  { id: 'lc_w3_d4', week: 3, day: 18, translationKey: 'plans.low_carb.w3_d4', totalKcal: 1850 },
  { id: 'lc_w3_d5', week: 3, day: 19, translationKey: 'plans.low_carb.w3_d5', totalKcal: 1850 },
  { id: 'lc_w3_d6', week: 3, day: 20, translationKey: 'plans.low_carb.w3_d6', totalKcal: 1850 },
  { id: 'lc_w3_d7', week: 3, day: 21, translationKey: 'plans.low_carb.w3_d7', totalKcal: 1850 },
  // SEMANA 4
  { id: 'lc_w4_d1', week: 4, day: 22, translationKey: 'plans.low_carb.w4_d1', totalKcal: 1850 },
  { id: 'lc_w4_d2', week: 4, day: 23, translationKey: 'plans.low_carb.w4_d2', totalKcal: 1850 },
  { id: 'lc_w4_d3', week: 4, day: 24, translationKey: 'plans.low_carb.w4_d3', totalKcal: 1850 },
  { id: 'lc_w4_d4', week: 4, day: 25, translationKey: 'plans.low_carb.w4_d4', totalKcal: 1850 },
  { id: 'lc_w4_d5', week: 4, day: 26, translationKey: 'plans.low_carb.w4_d5', totalKcal: 1850 },
  { id: 'lc_w4_d6', week: 4, day: 27, translationKey: 'plans.low_carb.w4_d6', totalKcal: 1850 },
  { id: 'lc_w4_d7', week: 4, day: 28, translationKey: 'plans.low_carb.w4_d7', totalKcal: 1850 },
];

export const VEGETARIAN_PLAN: DailyMenuPlan[] = [
  // SEMANA 1
  { id: 'v_w1_d1', week: 1, day: 1, translationKey: 'plans.vegetarian.w1_d1', totalKcal: 1750 },
  { id: 'v_w1_d2', week: 1, day: 2, translationKey: 'plans.vegetarian.w1_d2', totalKcal: 1750 },
  { id: 'v_w1_d3', week: 1, day: 3, translationKey: 'plans.vegetarian.w1_d3', totalKcal: 1750 },
  { id: 'v_w1_d4', week: 1, day: 4, translationKey: 'plans.vegetarian.w1_d4', totalKcal: 1750 },
  { id: 'v_w1_d5', week: 1, day: 5, translationKey: 'plans.vegetarian.w1_d5', totalKcal: 1750 },
  { id: 'v_w1_d6', week: 1, day: 6, translationKey: 'plans.vegetarian.w1_d6', totalKcal: 1750 },
  { id: 'v_w1_d7', week: 1, day: 7, translationKey: 'plans.vegetarian.w1_d7', totalKcal: 1750 },
  // SEMANA 2
  { id: 'v_w2_d1', week: 2, day: 8, translationKey: 'plans.vegetarian.w2_d1', totalKcal: 1750 },
  { id: 'v_w2_d2', week: 2, day: 9, translationKey: 'plans.vegetarian.w2_d2', totalKcal: 1750, warnings: ['high_sodium'] },
  { id: 'v_w2_d3', week: 2, day: 10, translationKey: 'plans.vegetarian.w2_d3', totalKcal: 1750 },
  { id: 'v_w2_d4', week: 2, day: 11, translationKey: 'plans.vegetarian.w2_d4', totalKcal: 1750 },
  { id: 'v_w2_d5', week: 2, day: 12, translationKey: 'plans.vegetarian.w2_d5', totalKcal: 1750 },
  { id: 'v_w2_d6', week: 2, day: 13, translationKey: 'plans.vegetarian.w2_d6', totalKcal: 1750 },
  { id: 'v_w2_d7', week: 2, day: 14, translationKey: 'plans.vegetarian.w2_d7', totalKcal: 1750 },
  // SEMANA 3
  { id: 'v_w3_d1', week: 3, day: 15, translationKey: 'plans.vegetarian.w3_d1', totalKcal: 1750 },
  { id: 'v_w3_d2', week: 3, day: 16, translationKey: 'plans.vegetarian.w3_d2', totalKcal: 1750 },
  { id: 'v_w3_d3', week: 3, day: 17, translationKey: 'plans.vegetarian.w3_d3', totalKcal: 1750 },
  { id: 'v_w3_d4', week: 3, day: 18, translationKey: 'plans.vegetarian.w3_d4', totalKcal: 1750 },
  { id: 'v_w3_d5', week: 3, day: 19, translationKey: 'plans.vegetarian.w3_d5', totalKcal: 1750 },
  { id: 'v_w3_d6', week: 3, day: 20, translationKey: 'plans.vegetarian.w3_d6', totalKcal: 1750, warnings: ['high_potassium'] },
  { id: 'v_w3_d7', week: 3, day: 21, translationKey: 'plans.vegetarian.w3_d7', totalKcal: 1750 },
  // SEMANA 4
  { id: 'v_w4_d1', week: 4, day: 22, translationKey: 'plans.vegetarian.w4_d1', totalKcal: 1750 },
  { id: 'v_w4_d2', week: 4, day: 23, translationKey: 'plans.vegetarian.w4_d2', totalKcal: 1750 },
  { id: 'v_w4_d3', week: 4, day: 24, translationKey: 'plans.vegetarian.w4_d3', totalKcal: 1750, warnings: ['high_sodium'] },
  { id: 'v_w4_d4', week: 4, day: 25, translationKey: 'plans.vegetarian.w4_d4', totalKcal: 1750 },
  { id: 'v_w4_d5', week: 4, day: 26, translationKey: 'plans.vegetarian.w4_d5', totalKcal: 1750 },
  { id: 'v_w4_d6', week: 4, day: 27, translationKey: 'plans.vegetarian.w4_d6', totalKcal: 1750 },
  { id: 'v_w4_d7', week: 4, day: 28, translationKey: 'plans.vegetarian.w4_d7', totalKcal: 1750 },
];

export interface ExerciseTemplate {
  name: string;
  description: string;
  defaultSec: number;
  category: "Mancuernas" | "Bici" | "Cuerpo libre";
  difficulty: "Básico" | "Intermedio" | "Quemagrasas";
  caloriesPerMinute: number;
}

export const EXERCISES: ExerciseTemplate[] = [
  { name: "Sentadillas (mancuernas)", description: "10 kg · 3 series · 12 reps", defaultSec: 60, category: "Mancuernas", difficulty: "Básico", caloriesPerMinute: 6 },
  { name: "Press militar", description: "Mancuernas 8-10 kg · 3 x 10", defaultSec: 60, category: "Mancuernas", difficulty: "Intermedio", caloriesPerMinute: 5 },
  { name: "Remo a una mano", description: "10 kg · 3 x 12 por brazo", defaultSec: 90, category: "Mancuernas", difficulty: "Básico", caloriesPerMinute: 6 },
  { name: "Curl de bíceps", description: "8-10 kg · 3 x 12", defaultSec: 60, category: "Mancuernas", difficulty: "Básico", caloriesPerMinute: 4 },
  { name: "Peso muerto rumano", description: "10 kg · 3 x 12", defaultSec: 60, category: "Mancuernas", difficulty: "Intermedio", caloriesPerMinute: 7 },
  { name: "Elevaciones laterales", description: "Mancuernas 4-6 kg · 3 x 15", defaultSec: 60, category: "Mancuernas", difficulty: "Básico", caloriesPerMinute: 4 },
  { name: "Bicicleta estática · suave", description: "Calentamiento 60-70 rpm", defaultSec: 600, category: "Bici", difficulty: "Básico", caloriesPerMinute: 5 },
  { name: "Bicicleta estática · HIIT", description: "Intervalos intensos 20s/10s", defaultSec: 600, category: "Bici", difficulty: "Quemagrasas", caloriesPerMinute: 12 },
  { name: "Bicicleta estática · resistencia", description: "Ritmo constante 80-90 rpm pesado", defaultSec: 1200, category: "Bici", difficulty: "Intermedio", caloriesPerMinute: 8 },
  { name: "Plancha abdominal", description: "Mantener postura", defaultSec: 45, category: "Cuerpo libre", difficulty: "Básico", caloriesPerMinute: 5 },
  { name: "Flexiones", description: "3 x 10-15 reps", defaultSec: 60, category: "Cuerpo libre", difficulty: "Intermedio", caloriesPerMinute: 8 },
  { name: "Burpees", description: "3 x 12 reps", defaultSec: 90, category: "Cuerpo libre", difficulty: "Quemagrasas", caloriesPerMinute: 15 },
  { name: "Jumping Jacks", description: "3 x 1 min", defaultSec: 60, category: "Cuerpo libre", difficulty: "Quemagrasas", caloriesPerMinute: 10 },
  { name: "Zancadas", description: "3 x 12 por pierna", defaultSec: 90, category: "Cuerpo libre", difficulty: "Básico", caloriesPerMinute: 7 }
];
