import { UserGoal } from './WorkoutEngine';

type Lang = 'es' | 'en' | 'de' | 'fr' | 'it';

const QUOTES: Record<UserGoal, Record<Lang, string[]>> = {
  lose: {
    es: [
      "El déficit calórico de hoy es el resultado de mañana.",
      "La grasa se oxida con paciencia, no se suda con desesperación.",
      "Tu metabolismo no está roto, solo necesita las señales correctas.",
      "El hambre emocional exige inmediatez, el cuerpo físico espera.",
      "No compensas un mal fin de semana, simplemente vuelves a tu plan.",
      "Pierde grasa en la cocina, gana salud en el movimiento.",
      "Beber agua no es opcional, es tu principal herramienta metabólica.",
      "La báscula mide la gravedad, no tu composición corporal real.",
      "Un déficit moderado prolongado vence a la restricción extrema.",
      "No estás a dieta, estás optimizando tu bioquímica.",
      "Cada gramo de fibra es una inversión en saciedad a largo plazo.",
      "El sueño de calidad es el secreto mejor guardado para perder grasa.",
      "Reduce los carbohidratos netos, no el volumen real de tu comida.",
      "La comida no es un premio ni el ejercicio es un castigo.",
      "Tu cuerpo refleja tus hábitos diarios, no tus intenciones.",
      "La consistencia imperfecta siempre supera a la perfección abandonada.",
      "El músculo que proteges hoy quemará la grasa de mañana.",
      "Celebra la pérdida de centímetros, el peso es solo un número.",
      "Caminar 10.000 pasos hace más por ti que una hora de culpa.",
      "Hoy eliges cómo funcionará tu cuerpo en los próximos seis meses."
    ],
    en: [
      "Today's caloric deficit is tomorrow's result.",
      "Fat oxidizes with patience, it is not sweated out with desperation.",
      "Your metabolism isn't broken, it just needs the right signals.",
      "Emotional hunger demands immediacy, the physical body waits.",
      "You don't compensate for a bad weekend, you simply return to your plan.",
      "Lose fat in the kitchen, gain health in movement.",
      "Drinking water is not optional, it is your main metabolic tool.",
      "The scale measures gravity, not your actual body composition.",
      "A prolonged moderate deficit beats extreme restriction.",
      "You are not on a diet, you are optimizing your biochemistry.",
      "Every gram of fiber is an investment in long-term satiety.",
      "Quality sleep is the best kept secret for fat loss.",
      "Reduce net carbohydrates, not the actual volume of your food.",
      "Food is not a reward and exercise is not a punishment.",
      "Your body reflects your daily habits, not your intentions.",
      "Imperfect consistency always beats abandoned perfection.",
      "The muscle you protect today will burn tomorrow's fat.",
      "Celebrate the loss of centimeters, weight is just a number.",
      "Walking 10,000 steps does more for you than an hour of guilt.",
      "Today you choose how your body will function in the next six months."
    ],
    de: [
      "Das heutige Kaloriendefizit ist das Ergebnis von morgen.",
      "Fett oxidiert mit Geduld, man schwitzt es nicht aus Verzweiflung aus.",
      "Dein Stoffwechsel ist nicht kaputt, er braucht nur die richtigen Signale.",
      "Emotionaler Hunger verlangt nach Sofortigkeit, der physische Körper wartet.",
      "Du gleichst ein schlechtes Wochenende nicht aus, du kehrst einfach zu deinem Plan zurück.",
      "Verliere Fett in der Küche, gewinne Gesundheit durch Bewegung.",
      "Wasser trinken ist nicht optional, es ist dein wichtigstes metabolisches Werkzeug.",
      "Die Waage misst die Schwerkraft, nicht deine tatsächliche Körperzusammensetzung.",
      "Ein anhaltendes moderates Defizit schlägt extreme Einschränkung.",
      "Du machst keine Diät, du optimierst deine Biochemie.",
      "Jedes Gramm Ballaststoffe ist eine Investition in langfristige Sättigung.",
      "Hochwertiger Schlaf ist das bestgehütete Geheimnis für den Fettabbau.",
      "Reduziere die Netto-Kohlenhydrate, nicht das tatsächliche Volumen deines Essens.",
      "Essen ist keine Belohnung und Bewegung ist keine Strafe.",
      "Dein Körper spiegelt deine täglichen Gewohnheiten wider, nicht deine Absichten.",
      "Unperfekte Beständigkeit schlägt immer aufgegebene Perfektion.",
      "Der Muskel, den du heute schützt, wird das Fett von morgen verbrennen.",
      "Feiere den Verlust von Zentimetern, das Gewicht ist nur eine Zahl.",
      "10.000 Schritte zu gehen bringt dir mehr als eine Stunde Schuldgefühle.",
      "Heute wählst du, wie dein Körper in den nächsten sechs Monaten funktionieren wird."
    ],
    fr: [
      "Le déficit calorique d'aujourd'hui est le résultat de demain.",
      "La graisse s'oxyde avec patience, elle ne se sue pas par désespoir.",
      "Ton métabolisme n'est pas cassé, il a juste besoin des bons signaux.",
      "La faim émotionnelle exige l'immédiateté, le corps physique attend.",
      "On ne compense pas un mauvais week-end, on retourne simplement à son plan.",
      "Perds de la graisse en cuisine, gagne en santé dans le mouvement.",
      "Boire de l'eau n'est pas optionnel, c'est ton principal outil métabolique.",
      "La balance mesure la gravité, pas ta véritable composition corporelle.",
      "Un déficit modéré prolongé l'emporte sur la restriction extrême.",
      "Tu n'es pas au régime, tu optimises ta biochimie.",
      "Chaque gramme de fibres est un investissement dans la satiété à long terme.",
      "Un sommeil de qualité est le secret le mieux gardé pour la perte de graisse.",
      "Réduis les glucides nets, pas le volume réel de ta nourriture.",
      "La nourriture n'est pas une récompense et l'exercice n'est pas une punition.",
      "Ton corps reflète tes habitudes quotidiennes, pas tes intentions.",
      "La constance imparfaite surpasse toujours la perfection abandonnée.",
      "Le muscle que tu protèges aujourd'hui brûlera la graisse de demain.",
      "Célèbre la perte de centimètres, le poids n'est qu'un chiffre.",
      "Marcher 10 000 pas fait plus pour toi qu'une heure de culpabilité.",
      "Aujourd'hui, tu choisis comment ton corps fonctionnera dans les six prochains mois."
    ],
    it: [
      "Il deficit calorico di oggi è il risultato di domani.",
      "Il grasso si ossida con pazienza, non si suda per disperazione.",
      "Il tuo metabolismo non è rotto, ha solo bisogno dei segnali giusti.",
      "La fame emotiva esige immediatezza, il corpo fisico aspetta.",
      "Non si compensa un cattivo fine settimana, si torna semplicemente al piano.",
      "Perdi grasso in cucina, guadagna salute nel movimento.",
      "Bere acqua non è facoltativo, è il tuo strumento metabolico principale.",
      "La bilancia misura la gravità, non la tua vera composizione corporea.",
      "Un deficit moderato prolungato batte l'estrema restrizione.",
      "Non sei a dieta, stai ottimizzando la tua biochimica.",
      "Ogni grammo di fibre è un investimento nella sazietà a lungo termine.",
      "Il sonno di qualità è il segreto meglio custodito per la perdita di grasso.",
      "Riduci i carboidrati netti, non il volume effettivo del tuo cibo.",
      "Il cibo non è un premio e l'esercizio non è una punizione.",
      "Il tuo corpo riflette le tue abitudini quotidiane, non le tue intenzioni.",
      "La coerenza imperfetta supera sempre la perfezione abbandonata.",
      "Il muscolo che proteggi oggi brucerà il grasso di domani.",
      "Celebra la perdita di centimetri, il peso è solo un numero.",
      "Camminare 10.000 passi fa più per te che un'ora di sensi di colpa.",
      "Oggi scegli come funzionerà il tuo corpo nei prossimi sei mesi."
    ]
  },
  maintain: {
    es: [
      "La constancia es tu mayor músculo.",
      "Mantenerse es la verdadera victoria del cambio de hábitos.",
      "No hay línea de meta, la salud es un estilo de vida continuo.",
      "El equilibrio no es estático, es un ajuste diario.",
      "Flexibilidad metabólica significa disfrutar sin retroceder.",
      "Tu peso de mantenimiento es donde tu salud y tu vida encajan.",
      "Celebra la ausencia de rebote; tu cuerpo ha aprendido.",
      "El movimiento diario ya no es una tarea, es tu naturaleza.",
      "Una comida fuera del plan no arruina semanas de disciplina.",
      "La báscula se detuvo, pero tu salud sigue avanzando.",
      "Ya conoces tus porciones; confía en tu intuición entrenada.",
      "Mantener el músculo cuesta menos energía que construirlo.",
      "Tu identidad ha cambiado: ahora eres una persona activa.",
      "El éxito silencioso es levantarse y cumplir sin pensarlo.",
      "La rutina saludable es tu armadura contra la regresión.",
      "Has dominado la técnica; ahora disfruta del proceso.",
      "Ya no luchas contra tu cuerpo, trabajas en equipo con él.",
      "Nutrirse bien ya no requiere esfuerzo mental, es automático.",
      "El verdadero progreso es que lo saludable te resulte normal.",
      "Mantener es el arte de la moderación sin privación."
    ],
    en: [
      "Consistency is your greatest muscle.",
      "Maintaining is the true victory of habit change.",
      "There is no finish line, health is a continuous lifestyle.",
      "Balance is not static, it is a daily adjustment.",
      "Metabolic flexibility means enjoying without going backwards.",
      "Your maintenance weight is where your health and your life fit together.",
      "Celebrate the absence of a rebound; your body has learned.",
      "Daily movement is no longer a chore, it is your nature.",
      "One off-plan meal does not ruin weeks of discipline.",
      "The scale stopped, but your health keeps advancing.",
      "You already know your portions; trust your trained intuition.",
      "Maintaining muscle costs less energy than building it.",
      "Your identity has changed: you are now an active person.",
      "Silent success is getting up and getting it done without overthinking.",
      "A healthy routine is your armor against regression.",
      "You have mastered the technique; now enjoy the process.",
      "You no longer fight against your body, you work as a team with it.",
      "Nourishing yourself well no longer requires mental effort, it is automatic.",
      "True progress is when the healthy choice feels normal to you.",
      "Maintaining is the art of moderation without deprivation."
    ],
    de: [
      "Beständigkeit ist dein größter Muskel.",
      "Das Halten des Gewichts ist der wahre Sieg der Gewohnheitsänderung.",
      "Es gibt keine Ziellinie, Gesundheit ist ein kontinuierlicher Lebensstil.",
      "Gleichgewicht ist nicht statisch, es ist eine tägliche Anpassung.",
      "Metabolische Flexibilität bedeutet, zu genießen, ohne Rückschritte zu machen.",
      "Dein Erhaltungsgewicht ist da, wo deine Gesundheit und dein Leben zusammenpassen.",
      "Feiere das Ausbleiben des Jo-Jo-Effekts; dein Körper hat gelernt.",
      "Tägliche Bewegung ist keine Pflicht mehr, sie ist deine Natur.",
      "Eine ungeplante Mahlzeit ruiniert nicht Wochen der Disziplin.",
      "Die Waage steht still, aber deine Gesundheit macht weiter Fortschritte.",
      "Du kennst deine Portionen bereits; vertraue deiner trainierten Intuition.",
      "Muskeln zu erhalten kostet weniger Energie als sie aufzubauen.",
      "Deine Identität hat sich verändert: Du bist jetzt ein aktiver Mensch.",
      "Der stille Erfolg ist, aufzustehen und es einfach zu tun, ohne nachzudenken.",
      "Eine gesunde Routine ist deine Rüstung gegen den Rückfall.",
      "Du hast die Technik gemeistert; genieße nun den Prozess.",
      "Du kämpfst nicht mehr gegen deinen Körper, du arbeitest als Team mit ihm.",
      "Sich gut zu ernähren erfordert keine geistige Anstrengung mehr, es passiert automatisch.",
      "Der wahre Fortschritt ist, wenn dir das Gesunde normal vorkommt.",
      "Erhaltung ist die Kunst der Mäßigung ohne Entbehrung."
    ],
    fr: [
      "La constance est ton plus grand muscle.",
      "Se maintenir est la véritable victoire du changement d'habitudes.",
      "Il n'y a pas de ligne d'arrivée, la santé est un mode de vie continu.",
      "L'équilibre n'est pas statique, c'est un ajustement quotidien.",
      "La flexibilité métabolique signifie profiter sans reculer.",
      "Ton poids de maintien est là où ta santé et ta vie s'accordent.",
      "Célèbre l'absence de rebond ; ton corps a appris.",
      "Le mouvement quotidien n'est plus une corvée, c'est ta nature.",
      "Un repas hors plan ne ruine pas des semaines de discipline.",
      "La balance s'est arrêtée, mais ta santé continue de progresser.",
      "Tu connais déjà tes portions ; fais confiance à ton intuition entraînée.",
      "Maintenir le muscle coûte moins d'énergie que le construire.",
      "Ton identité a changé : tu es maintenant une personne active.",
      "Le succès silencieux, c'est se lever et accomplir sans y penser.",
      "La routine saine est ton armure contre la régression.",
      "Tu as maîtrisé la technique ; maintenant profite du processus.",
      "Tu ne luttes plus contre ton corps, tu fais équipe avec lui.",
      "Bien se nourrir ne demande plus d'effort mental, c'est automatique.",
      "Le vrai progrès, c'est quand ce qui est sain te paraît normal.",
      "Le maintien est l'art de la modération sans privation."
    ],
    it: [
      "La coerenza è il tuo muscolo più grande.",
      "Mantenersi è la vera vittoria del cambiamento di abitudini.",
      "Non c'è linea del traguardo, la salute è uno stile di vita continuo.",
      "L'equilibrio non è statico, è un aggiustamento quotidiano.",
      "Flessibilità metabolica significa godere senza regredire.",
      "Il tuo peso di mantenimento è dove la tua salute e la tua vita combaciano.",
      "Celebra l'assenza di rimbalzo; il tuo corpo ha imparato.",
      "Il movimento quotidiano non è più un compito, è la tua natura.",
      "Un pasto fuori programma non rovina settimane di disciplina.",
      "La bilancia si è fermata, ma la tua salute continua ad avanzare.",
      "Conosci già le tue porzioni; fidati della tua intuizione allenata.",
      "Mantenere il muscolo costa meno energia che costruirlo.",
      "La tua identità è cambiata: ora sei una persona attiva.",
      "Il successo silenzioso è alzarsi e compiere il dovere senza pensarci.",
      "La routine sana è la tua armatura contro la regressione.",
      "Hai padroneggiato la tecnica; ora goditi il processo.",
      "Non combatti più contro il tuo corpo, fai squadra con esso.",
      "Nutrirsi bene non richiede più sforzo mentale, è automatico.",
      "Il vero progresso è quando ciò che è sano ti sembra normale.",
      "Il mantenimento è l'arte della moderazione senza privazione."
    ]
  },
  gain: {
    es: [
      "Rompe las fibras hoy, constrúyelas esta noche.",
      "Si no hay tensión mecánica, no hay adaptación muscular.",
      "El superávit calórico es el ladrillo; el entrenamiento, el arquitecto.",
      "Descansar es el momento exacto en que realmente creces.",
      "Deja el ego en la puerta; controla siempre la fase excéntrica.",
      "Empujar cerca del fallo es donde ocurre la hipertrofia.",
      "Más proteína no siempre es mejor; el estímulo es el rey.",
      "Un músculo fuerte protege tus articulaciones y tu futuro.",
      "La fuerza central (core) es la base de todo crecimiento real.",
      "Sobrecarga progresiva: haz hoy más de lo que hiciste el mes pasado.",
      "No levantes pesas al azar, contrae músculos con intención.",
      "El dolor articular no es el objetivo, la fatiga muscular sí lo es.",
      "Alimenta tu recuperación con carbohidratos de alta calidad.",
      "Duerme como si fuera la parte más importante de tu entrenamiento.",
      "La técnica perfecta supera siempre a la carga excesiva.",
      "Conecta tu mente con el músculo que estás trabajando.",
      "Tu límite mental suele aparecer antes que tu fallo físico.",
      "Rango de movimiento completo equivale a desarrollo muscular completo.",
      "La paciencia es la carga más pesada que levantarás en este proceso.",
      "El músculo es tejido metabólicamente activo; constrúyelo como tu motor."
    ],
    en: [
      "Break the fibers today, build them tonight.",
      "If there is no mechanical tension, there is no muscle adaptation.",
      "The caloric surplus is the brick; the training is the architect.",
      "Resting is the exact moment when you actually grow.",
      "Leave your ego at the door; always control the eccentric phase.",
      "Pushing close to failure is where hypertrophy happens.",
      "More protein isn't always better; the stimulus is king.",
      "A strong muscle protects your joints and your future.",
      "Core strength is the foundation of all real growth.",
      "Progressive overload: do more today than you did last month.",
      "Don't lift weights randomly, contract muscles with intention.",
      "Joint pain is not the goal, muscle fatigue is.",
      "Fuel your recovery with high-quality carbohydrates.",
      "Sleep as if it were the most important part of your workout.",
      "Perfect technique always beats excessive load.",
      "Connect your mind with the muscle you are working.",
      "Your mental limit usually appears before your physical failure.",
      "Full range of motion equals full muscle development.",
      "Patience is the heaviest load you will lift in this process.",
      "Muscle is metabolically active tissue; build it as your engine."
    ],
    de: [
      "Zerstöre die Fasern heute, baue sie heute Nacht wieder auf.",
      "Wenn es keine mechanische Spannung gibt, gibt es keine Muskelanpassung.",
      "Der Kalorienüberschuss ist der Ziegelstein; das Training ist der Architekt.",
      "Das Ausruhen ist genau der Moment, in dem du wirklich wächst.",
      "Lass dein Ego an der Tür; kontrolliere immer die exzentrische Phase.",
      "Das Training nahe am Muskelversagen ist der Ort, an dem Hypertrophie entsteht.",
      "Mehr Protein ist nicht immer besser; der Reiz ist der König.",
      "Ein starker Muskel schützt deine Gelenke und deine Zukunft.",
      "Die Rumpfkraft (Core) ist die Basis für jedes echte Wachstum.",
      "Progressive Überlastung: Leiste heute mehr als letzten Monat.",
      "Hebe nicht einfach blind Gewichte, kontrahiere die Muskeln mit Absicht.",
      "Gelenkschmerzen sind nicht das Ziel, Muskelermüdung hingegen schon.",
      "Versorge deine Erholung mit hochwertigen Kohlenhydraten.",
      "Schlafe so, als wäre es der wichtigste Teil deines Trainings.",
      "Perfekte Technik schlägt immer übermäßiges Gewicht.",
      "Verbinde deinen Geist mit dem Muskel, den du gerade trainierst.",
      "Deine mentale Grenze taucht meistens vor deinem körperlichen Versagen auf.",
      "Der volle Bewegungsradius entspricht einer vollständigen Muskelentwicklung.",
      "Geduld ist die schwerste Last, die du in diesem Prozess heben wirst.",
      "Muskeln sind stoffwechselaktives Gewebe; baue sie wie deinen Motor auf."
    ],
    fr: [
      "Brise les fibres aujourd'hui, construis-les cette nuit.",
      "S'il n'y a pas de tension mécanique, il n'y a pas d'adaptation musculaire.",
      "L'excédent calorique est la brique ; l'entraînement est l'architecte.",
      "Le repos est le moment exact où tu grandis réellement.",
      "Laisse ton ego à la porte ; contrôle toujours la phase excentrique.",
      "Pousser près de l'échec est là où se produit l'hypertrophie.",
      "Plus de protéines n'est pas toujours mieux ; le stimulus est roi.",
      "Un muscle fort protège tes articulations et ton avenir.",
      "La force centrale (core) est la base de toute véritable croissance.",
      "Surcharge progressive : fais plus aujourd'hui que le mois dernier.",
      "Ne soulève pas de poids au hasard, contracte tes muscles avec intention.",
      "La douleur articulaire n'est pas le but, la fatigue musculaire oui.",
      "Alimente ta récupération avec des glucides de haute qualité.",
      "Dors comme si c'était la partie la plus importante de ton entraînement.",
      "Une technique parfaite l'emporte toujours sur une charge excessive.",
      "Connecte ton esprit avec le muscle que tu travailles.",
      "Ta limite mentale apparaît généralement avant ton échec physique.",
      "Une amplitude de mouvement complète équivaut à un développement musculaire complet.",
      "La patience est la charge la plus lourde que tu soulèveras dans ce processus.",
      "Le muscle est un tissu métaboliquement actif ; construis-le comme ton moteur."
    ],
    it: [
      "Rompi le fibre oggi, costruiscile stanotte.",
      "Se non c'è tensione meccanica, non c'è adattamento muscolare.",
      "Il surplus calorico è il mattone; l'allenamento è l'architetto.",
      "Riposare è il momento esatto in cui cresci veramente.",
      "Lascia l'ego alla porta; controlla sempre la fase eccentrica.",
      "Spingere vicino al cedimento è dove avviene l'ipertrofia.",
      "Più proteine non è sempre meglio; lo stimolo è il re.",
      "Un muscolo forte protegge le tue articolazioni e il tuo futuro.",
      "La forza centrale (core) è la base di ogni vera crescita.",
      "Sovraccarico progressivo: fai più oggi di quanto hai fatto il mese scorso.",
      "Non sollevare pesi a caso, contrai i muscoli con intenzione.",
      "Il dolore articolare non è l'obiettivo, l'affaticamento muscolare lo è.",
      "Alimenta il tuo recupero con carboidrati di alta qualità.",
      "Dormi come se fosse la parte più importante del tuo allenamento.",
      "La tecnica perfetta supera sempre il carico eccessivo.",
      "Connetti la tua mente con il muscolo che stai allenando.",
      "Il tuo limite mentale appare di solito prima del tuo cedimento fisico.",
      "Un raggio di movimento completo equivale a uno sviluppo muscolare completo.",
      "La pazienza è il carico più pesante che solleverai in questo processo.",
      "Il muscolo è tessuto metabolicamente attivo; costruiscilo come il tuo motore."
    ]
  }
};

export class MotivationEngine {
  /**
   * Returns a random motivational quote based on the user's goal and language.
   * Falls back to Spanish if the requested language is not found.
   */
  static getRandomQuote(goal: UserGoal, lang: string): string {
    const goalQuotes = QUOTES[goal];
    if (!goalQuotes) return '';
    
    const normalizedLang = lang.split('-')[0] as Lang;
    const langQuotes = goalQuotes[normalizedLang] || goalQuotes['es'];
    
    if (!langQuotes || langQuotes.length === 0) return '';
    
    return langQuotes[Math.floor(Math.random() * langQuotes.length)];
  }
}
