export const COMMON_FOODS: CommonFood[] = [  {
    translationKey: "chicken",
    calories: 110,
    protein: 23,
    carbs: 0,
    fat: 1.2,
    fiber: 0,
    ig: null,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "turkey",
    calories: 105,
    protein: 24,
    carbs: 0,
    fat: 1,
    fiber: 0,
    ig: null,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "egg",
    calories: 143,
    protein: 12.5,
    carbs: 0.7,
    fat: 9.5,
    fiber: 0,
    ig: null,
    sodiumLevel: "Medio"
  },  {
    translationKey: "salmon",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    ig: null,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "hake",
    calories: 89,
    protein: 18,
    carbs: 0,
    fat: 2,
    fiber: 0,
    ig: null,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "canned_tuna",
    calories: 116,
    protein: 26,
    carbs: 0,
    fat: 1,
    fiber: 0,
    ig: null,
    sodiumLevel: "Alto"
  },  {
    translationKey: "tofu",
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    fiber: 1.5,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "pork_loin",
    calories: 200,
    protein: 32,
    carbs: 0,
    fat: 8,
    fiber: 0,
    ig: null,
    sodiumLevel: "Alto"
  },  {
    translationKey: "prawns",
    calories: 99,
    protein: 24,
    carbs: 0,
    fat: 0.3,
    fiber: 0,
    ig: null,
    sodiumLevel: "Medio"
  },  {
    translationKey: "beef_lean",
    calories: 130,
    protein: 21,
    carbs: 0,
    fat: 5,
    fiber: 0,
    ig: null,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "cod",
    calories: 82,
    protein: 18,
    carbs: 0,
    fat: 0.7,
    fiber: 0,
    ig: null,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "sardines",
    calories: 208,
    protein: 24,
    carbs: 0,
    fat: 11,
    fiber: 0,
    ig: null,
    sodiumLevel: "Medio"
  },  {
    translationKey: "rabbit",
    calories: 136,
    protein: 20,
    carbs: 0,
    fat: 5.5,
    fiber: 0,
    ig: null,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "tempeh",
    calories: 193,
    protein: 19,
    carbs: 9,
    fat: 11,
    fiber: 6,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "seitan",
    calories: 370,
    protein: 75,
    carbs: 14,
    fat: 1.9,
    fiber: 0.6,
    ig: 15,
    sodiumLevel: "Alto"
  },  {
    translationKey: "cottage_cheese",
    calories: 98,
    protein: 11,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    ig: 10,
    sodiumLevel: "Medio"
  },  {
    translationKey: "skyr",
    calories: 65,
    protein: 11,
    carbs: 4,
    fat: 0.2,
    fiber: 0,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "egg_white",
    calories: 52,
    protein: 11,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0,
    ig: null,
    sodiumLevel: "Medio"
  },  {
    translationKey: "whey_protein",
    calories: 375,
    protein: 80,
    carbs: 5,
    fat: 3,
    fiber: 0,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "octopus",
    calories: 82,
    protein: 15,
    carbs: 2.2,
    fat: 1,
    fiber: 0,
    ig: null,
    sodiumLevel: "Medio"
  },  {
    translationKey: "oats",
    calories: 368,
    protein: 13,
    carbs: 64,
    fat: 7,
    fiber: 10,
    ig: 40,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "lentils",
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 8,
    ig: 25,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "chickpeas",
    calories: 164,
    protein: 9,
    carbs: 27,
    fat: 2.6,
    fiber: 7,
    ig: 30,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "quinoa",
    calories: 120,
    protein: 4.4,
    carbs: 21,
    fat: 1.9,
    fiber: 2.8,
    ig: 35,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "potato",
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.2,
    ig: 70,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "sweet_potato",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    ig: 50,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "brown_rice",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    ig: 50,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "rye_bread",
    calories: 250,
    protein: 9,
    carbs: 46,
    fat: 3.3,
    fiber: 6,
    ig: 45,
    sodiumLevel: "Medio"
  },  {
    translationKey: "whole_pasta",
    calories: 124,
    protein: 5,
    carbs: 25,
    fat: 1,
    fiber: 3,
    ig: 45,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "black_beans",
    calories: 132,
    protein: 9,
    carbs: 23,
    fat: 0.5,
    fiber: 9,
    ig: 30,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "couscous",
    calories: 112,
    protein: 3.8,
    carbs: 23,
    fat: 0.2,
    fiber: 1.4,
    ig: 45,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "buckwheat",
    calories: 343,
    protein: 13,
    carbs: 71,
    fat: 3.4,
    fiber: 10,
    ig: 50,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "millet",
    calories: 378,
    protein: 11,
    carbs: 72,
    fat: 4.2,
    fiber: 8.5,
    ig: 55,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "peas",
    calories: 81,
    protein: 5,
    carbs: 14,
    fat: 0.4,
    fiber: 5,
    ig: 35,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "broad_beans",
    calories: 88,
    protein: 8,
    carbs: 10,
    fat: 0.6,
    fiber: 5,
    ig: 40,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "corn_cakes",
    calories: 387,
    protein: 8,
    carbs: 80,
    fat: 3,
    fiber: 4,
    ig: 85,
    sodiumLevel: "Medio"
  },  {
    translationKey: "cassava",
    calories: 160,
    protein: 1.4,
    carbs: 38,
    fat: 0.3,
    fiber: 1.8,
    ig: 55,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "bulgur",
    calories: 342,
    protein: 12,
    carbs: 76,
    fat: 1.3,
    fiber: 18,
    ig: 48,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "corn",
    calories: 86,
    protein: 3.2,
    carbs: 19,
    fat: 1.2,
    fiber: 2.7,
    ig: 55,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "amaranth",
    calories: 371,
    protein: 14,
    carbs: 65,
    fat: 7,
    fiber: 7,
    ig: 35,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "spinach",
    calories: 23,
    protein: 3,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "broccoli",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "zucchini",
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "asparagus",
    calories: 20,
    protein: 2.2,
    carbs: 3.7,
    fat: 0.1,
    fiber: 2.1,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "tomato",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "red_pepper",
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "cucumber",
    calories: 15,
    protein: 0.6,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "eggplant",
    calories: 25,
    protein: 1,
    carbs: 6,
    fat: 0.2,
    fiber: 3,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "cauliflower",
    calories: 25,
    protein: 2,
    carbs: 5,
    fat: 0.3,
    fiber: 2,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "mushrooms",
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "artichoke",
    calories: 47,
    protein: 3.3,
    carbs: 11,
    fat: 0.2,
    fiber: 5,
    ig: 20,
    sodiumLevel: "Medio"
  },  {
    translationKey: "onion",
    calories: 40,
    protein: 1.1,
    carbs: 9,
    fat: 0.1,
    fiber: 1.7,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "carrot",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    ig: 35,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "celery",
    calories: 16,
    protein: 0.7,
    carbs: 3,
    fat: 0.2,
    fiber: 1.6,
    ig: 15,
    sodiumLevel: "Alto"
  },  {
    translationKey: "radish",
    calories: 16,
    protein: 0.7,
    carbs: 3.4,
    fat: 0.1,
    fiber: 1.6,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "lambs_lettuce",
    calories: 21,
    protein: 2,
    carbs: 2,
    fat: 0.4,
    fiber: 1.5,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "arugula",
    calories: 25,
    protein: 2.6,
    carbs: 3.7,
    fat: 0.7,
    fiber: 1.6,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "green_beans",
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.2,
    fiber: 2.7,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "red_cabbage",
    calories: 31,
    protein: 1.4,
    carbs: 7,
    fat: 0.2,
    fiber: 2.1,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "leek",
    calories: 61,
    protein: 1.5,
    carbs: 14,
    fat: 0.3,
    fiber: 1.8,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "chard",
    calories: 19,
    protein: 1.8,
    carbs: 3.7,
    fat: 0.2,
    fiber: 1.6,
    ig: 15,
    sodiumLevel: "Alto"
  },  {
    translationKey: "escarole",
    calories: 17,
    protein: 1.2,
    carbs: 3.4,
    fat: 0.2,
    fiber: 3.1,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "endive",
    calories: 17,
    protein: 0.9,
    carbs: 4,
    fat: 0.1,
    fiber: 3.1,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "brussels_sprouts",
    calories: 43,
    protein: 3.4,
    carbs: 9,
    fat: 0.3,
    fiber: 3.8,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "fennel",
    calories: 31,
    protein: 1.2,
    carbs: 7,
    fat: 0.2,
    fiber: 3.1,
    ig: 15,
    sodiumLevel: "Medio"
  },  {
    translationKey: "pumpkin",
    calories: 26,
    protein: 1,
    carbs: 6.5,
    fat: 0.1,
    fiber: 0.5,
    ig: 75,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "garlic",
    calories: 149,
    protein: 6.4,
    carbs: 33,
    fat: 0.5,
    fiber: 2.1,
    ig: 30,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "chili",
    calories: 40,
    protein: 1.9,
    carbs: 9,
    fat: 0.4,
    fiber: 1.5,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "okra",
    calories: 33,
    protein: 1.9,
    carbs: 7,
    fat: 0.2,
    fiber: 3.2,
    ig: 20,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "soy_sprouts",
    calories: 30,
    protein: 3,
    carbs: 6,
    fat: 0.2,
    fiber: 1.8,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "olive_oil",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    ig: null,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "avocado",
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
    ig: 10,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "walnuts",
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 7,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "almonds",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "chia_seeds",
    calories: 486,
    protein: 17,
    carbs: 42,
    fat: 31,
    fiber: 34,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "peanut_butter",
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "pistachios",
    calories: 562,
    protein: 20,
    carbs: 28,
    fat: 45,
    fiber: 10,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "flaxseed",
    calories: 534,
    protein: 18,
    carbs: 29,
    fat: 42,
    fiber: 27,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "pumpkin_seeds",
    calories: 559,
    protein: 30,
    carbs: 10,
    fat: 49,
    fiber: 6,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "olives",
    calories: 115,
    protein: 0.8,
    carbs: 6,
    fat: 10,
    fiber: 3.2,
    ig: 15,
    sodiumLevel: "Alto"
  },  {
    translationKey: "cashews",
    calories: 553,
    protein: 18,
    carbs: 30,
    fat: 44,
    fiber: 3.3,
    ig: 20,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "hazelnuts",
    calories: 628,
    protein: 15,
    carbs: 17,
    fat: 61,
    fiber: 10,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "coconut_oil",
    calories: 862,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    ig: null,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "ghee",
    calories: 899,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    ig: null,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "macadamia",
    calories: 718,
    protein: 8,
    carbs: 14,
    fat: 76,
    fiber: 8.6,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "blueberries",
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    fiber: 2.4,
    ig: 25,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "apple",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    ig: 35,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "banana",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    ig: 50,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "strawberries",
    calories: 32,
    protein: 0.7,
    carbs: 8,
    fat: 0.3,
    fiber: 2,
    ig: 25,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "lemon",
    calories: 29,
    protein: 1.1,
    carbs: 9,
    fat: 0.3,
    fiber: 2.8,
    ig: 20,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "greek_yogurt",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "quark",
    calories: 68,
    protein: 12,
    carbs: 4,
    fat: 0.2,
    fiber: 0,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "kefir",
    calories: 37,
    protein: 3.3,
    carbs: 4,
    fat: 1,
    fiber: 0,
    ig: 15,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "kiwi",
    calories: 61,
    protein: 1.1,
    carbs: 15,
    fat: 0.5,
    fiber: 3,
    ig: 50,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "orange",
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    ig: 40,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "pineapple",
    calories: 50,
    protein: 0.5,
    carbs: 13,
    fat: 0.1,
    fiber: 1.4,
    ig: 59,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "papaya",
    calories: 43,
    protein: 0.5,
    carbs: 11,
    fat: 0.3,
    fiber: 1.7,
    ig: 58,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "watermelon",
    calories: 30,
    protein: 0.6,
    carbs: 8,
    fat: 0.2,
    fiber: 0.4,
    ig: 72,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "raspberries",
    calories: 52,
    protein: 1.2,
    carbs: 12,
    fat: 0.7,
    fiber: 6.5,
    ig: 25,
    sodiumLevel: "Bajo"
  },  {
    translationKey: "blackberry",
    calories: 43,
    protein: 1.4,
    carbs: 10,
    fat: 0.5,
    fiber: 5.3,
    ig: 25,
    sodiumLevel: "Bajo"
  }
];